/* =========================
   SETTING UP PROD DATABASE
   ========================= */

DROP DATABASE IF EXISTS prod;
CREATE DATABASE prod;
USE prod;

DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS parking;

CREATE TABLE parking (
    PARKING_NUMBER INT PRIMARY KEY,
    AVAILABLE BOOLEAN NOT NULL,
    TYPE VARCHAR(10) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE ticket (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PARKING_NUMBER INT NOT NULL,
    VEHICLE_REG_NUMBER VARCHAR(10) NOT NULL,
    PRICE DOUBLE,
    IN_TIME DATETIME NOT NULL,
    OUT_TIME DATETIME,
    CONSTRAINT fk_ticket_parking
        FOREIGN KEY (PARKING_NUMBER)
        REFERENCES parking(PARKING_NUMBER)
) ENGINE=InnoDB;

/* Parking spots */
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (1, true, 'CAR');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (2, true, 'CAR');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (3, true, 'CAR');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (4, true, 'BIKE');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (5, true, 'BIKE');

COMMIT;


/* =========================
   SETTING UP TEST DATABASE
   ========================= */

DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
USE test;

DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS parking;

CREATE TABLE parking (
    PARKING_NUMBER INT PRIMARY KEY,
    AVAILABLE BOOLEAN NOT NULL,
    TYPE VARCHAR(10) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE ticket (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PARKING_NUMBER INT NOT NULL,
    VEHICLE_REG_NUMBER VARCHAR(10) NOT NULL,
    PRICE DOUBLE,
    IN_TIME DATETIME NOT NULL,
    OUT_TIME DATETIME,
    CONSTRAINT fk_ticket_parking_test
        FOREIGN KEY (PARKING_NUMBER)
        REFERENCES parking(PARKING_NUMBER)
) ENGINE=InnoDB;

/* Parking spots */
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (1, true, 'CAR');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (2, true, 'CAR');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (3, true, 'CAR');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (4, true, 'BIKE');
INSERT INTO parking (PARKING_NUMBER, AVAILABLE, TYPE) VALUES (5, true, 'BIKE');

COMMIT;
